name: Update README_en.md

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  translate-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install googletrans==4.0.0-rc1

      - name: Translate README.md to README_en.md
        run: python .github/scripts/translate_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README_en.md
          git commit -m "Auto update README_en.md from README.md" || echo "No changes"
          git push
